### ISSUE TITLE
fix support of ARM platforms

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel#1]
This issue has been rcouch/rcouch#29.

**Comment by davidoccam** [comment]
For your information

pi@raspberrypi ~/barrel-alpha-1 $ grep -R '__cxa_guard_release'

Binary file _build/prod/lib/jiffy/priv/jiffy.so matches
Binary file _build/prod/lib/jiffy/c_src/double-conversion/double-conversion.o matches
Binary file _build/prod/rel/barrel/lib/jiffy-0.0.0+build.117.refb162efd/priv/jiffy.so matches
Binary file _build/prod/rel/barrel/lib/jiffy-0.0.0+build.117.refb162efd/c_src/double-conversion/double-conversion.o matches

_build/prod/rel/barrel/log/couch.log:[21:04:57.871 UTC] [<0.2134.0>] [warning] 

The on_load function for module jiffy returned {error,{load_failed,"Failed to load NIF library: '/home/pi/barrel-alpha-1/_build/prod/rel/barrel/lib/jiffy-0.0.0+build.117.refb162efd/priv/jiffy.so: undefined symbol: __cxa_guard_release'"}}

Binary file _build/default/lib/jiffy/priv/jiffy.so matches
Binary file _build/default/lib/jiffy/c_src/double-conversion/double-conversion.o matches

pi@raspberrypi ~/barrel-alpha-1 $

**Comment by nrdufour** [comment]
Yep I've got the exact issue on the udoo (armv7).

**Comment by nrdufour** [comment]
OK I found the issue: the Makefile in the jiffy c_src dir is missing the following after line 24:
```
LDFLAGS ?= -lstdc++
```

**Comment by benoitc** [comment]
@nrdufour thanks!

@davidoccam can you also test the patch given by @nrdufour . I created a specific branch in jiffy for it. Will test myself later in the day.

**Comment by davidoccam** [comment]
tested with @nrdufour patch --same result which signifies to me that NIF code failed to configure and compile silently. That is produced no ( visible to me ) error messages to indicate the failure.

Compile failure was in the past caused by wrong compiler flags for the raspbian GCC version which was for armv6. 

Although the raspberry pi 2 is "checking host system type... armv7l-unknown-linux-gnu"
the flags are for the GCC COMPILER version which are for the compatibility option of the SOC to run arnv6 code.
All raspbian C code is for armv6 for compatibility with all previous Raspberry pi code.

my previous patches hack for spidermonkey compile were;

pi@raspberrypi ~/rcouch-newbuild/apps/couch/patches/js $ nano patch-configure
@@ -13326,9 +13326,9 @@
 #define MOZ_ARM_ARCH 1
 EOF

-        CFLAGS="$CFLAGS -march=armv7-a -marm -mfloat-abi=softfp $MOZ_ARM_VFP_$
-        CXXFLAGS="$CXXFLAGS -march=armv7-a -marm -mfloat-abi=softfp $MOZ_ARM_$
-        ASFLAGS="$ASFLAGS -march=armv7-a -marm -mfloat-abi=softfp $MOZ_ARM_VF$
+        CFLAGS="-O2 -mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
+        CXXFLAGS="-O2 -mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
+        ASFLAGS="-O2 -mcpu=arm1176jzf-s -mfpu=vfp -mfloat-abi=hard"
       else
         { echo "configure: error: --with-cpu-arch=armv7 is not supported for for non-GNU toolchains" 1>&2; exit 1; }
       fi

I hope this may help.

**Comment by benoitc** [comment]
I have not received my raspberry 2 yet but I will try on the normal B and udoo asap.

**Comment by benoitc** [comment]
@davidoccam reopened the issue.

**Comment by benoitc** [comment]
imo this issue happen because we are mixing  C++ and CC code. Maybe the following change would do the trick:

    diff --git a/c_src/Makefile b/c_src/Makefile
    index f12cba0..73a3c71 100755
    --- a/c_src/Makefile
    +++ b/c_src/Makefile
    @@ -21,7 +21,7 @@ else ifeq ($(UNAME_SYS), FreeBSD)
            CFLAGS ?= -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes
            CXXFLAGS ?= -O3 -finline-functions -Wall
     else ifeq ($(UNAME_SYS), Linux)
    -       CC ?= gcc
    +       CC ?= g++
            CFLAGS ?= -O3 -std=c99 -finline-functions -Wall -Wmissing-prototypes
            CXXFLAGS ?= -O3 -finline-functions -Wall
            LDFLAGS ?= -lstdc++

**Comment by davidoccam** [comment]
barrel-alpha2 tested on raspberrypi2

{"couchdb":"Welcome","uuid":"50373aa377f9b05b6970fb5992dd4295","version":"1.8.2","vendor":{"version":"1.0.0-alpha-2","name":"barrel"}}

Verify Your Installation.  Your installation looks fine. Time to Relax.

Thanks for your sleuthing , I can now appreciate the work you have done with rebar3 and all the other informative developments.

**Comment by nrdufour** [comment]
Very cool!
