### ISSUE TITLE
Issues with `_changes` feed

### ISSUE THREAD

**Issue by josip** [barrel-db/barrel#18]
There a couple of issues we found with `_changes` feed:

- [x] `descending=true`
  * `last_seq` is incorrect as it's of the last change in the `results` array, but not the logical last change ie. first element of `results` in this case
  * when used with `filter=_view` it returns one row less than the same query with `descending=false`

- [x] `filter=_view&since=now`
  * `last_seq` in the response is that of the DB, not the view

- [x] `since=9999999`
  * not sure if it's a bug or an expected behaviour (applies to standard `_changes` feed too)
  * if  `since` is bigger than actual `last_seq` of the DB/view, `last_seq` in the response will be whatever we've passed in. Expected behaviour would be that the actual `last_seq` is returned in this case.

**Comment by benoitc** [comment]
@josip find below some questions regarding this issue. I will take care about the other topics.

> - [ ] `descending=true`
>  * `last_seq` is incorrect as it's of the last change in the `results` array, but not the logical last change ie. first element of `results` in this case

Well actually the same behaviour apply to the normal change. That sounds logical anyway since the last seq is the last sequence actually returned in the reverse order, so the first sequence indexed in the view change. I don't think this behaviour should be changed.

> - [ ] `since=9999999`
>   * not sure if it's a bug or an expected behaviour (applies to standard `_changes` feed too)
>   * if  `since` is bigger than actual `last_seq` of the DB/view, `last_seq` in the response will be whatever we've passed in. Expected behaviour would be that the actual `last_seq` is returned in this case.

Do you mean when `Descending=false` ?

**Comment by josip** [comment]
@benoitc correct, `descending=false` in second case. Again, as with the first thing you've mentioned, it's a matter of perspective/usecase.

**Comment by benoitc** [comment]
@josip what about adding a `start_seq` property? Then you would only have to compare both. Thoughts?

**Comment by benoitc** [comment]
ca48b74c6e22832575e457413c7ca6a947194772 exactly does that. cc @josip

**Comment by benoitc** [comment]
@josip 
> - [ ] `since=9999999`
>   * not sure if it's a bug or an expected behaviour (applies to standard `_changes` feed too)
>  * if  `since` is bigger than actual `last_seq` of the DB/view, `last_seq` in the response will be whatever we've passed in. Expected behaviour would be that the actual `last_seq` is returned in this case.

There is a possible race condition there if we try to return the "real" last sequence. It may or may not be the last one. Also it complicate the way to handle the change feeds since we need to track the type of filter to make the last call.

Also at start we can't do it, ie. we can't replace the sequence requested by the real last sequence. Indeed some may wait for a future sequence in the change feed.  Which may be useful in some cases.

I would mark that one as `WONT'T FIX` . With the addition of the `start_seq`  property.
